title: "slama.dev"
description: "Tomáš Sláma's personal website."
url: "https://slama.dev"

baseurl: ""

# exclude Jekyll-related files, scripts and generated content
exclude: [
  "ignored/",
  "scripts/",
  "makefile",
  "LICENSE.txt",
  "**/README.md",
  "**/ignored",
  "README.md",
  "climbing/journal.yaml",
  "climbing/videos.yaml",
  "climbing/*.py",
  "*.xopp",
  "assets/productivincrement.py"
]

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

permalink: /:slugified_categories/:title/

jektex:
  silent: true

plugins:
- jekyll-redirect-from
